TC1/urls.py
from django.contrib import admin
from django.urls import include, path
from attendance import views
from django.views.i18n import JavaScriptCatalog
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('attendance/', include('attendance.urls')),
    path('', views.landing_page, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('chaining/', include('smart_selects.urls')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    
]
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey
from django.urls import reverse

# Create your models here.

class State(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Local_govt(models.Model):
    name = models.CharField(max_length=255)
    state = models.ForeignKey(State, on_delete=models.PROTECT, related_name='local_government' )

    def __str__(self):
        return self.name

class Student(models.Model):
    surname = models.CharField(max_length=50)
    firstname = models.CharField(max_length=50)
    middlename = models.CharField(max_length=50, null=True, blank=True)
    birthday = models.DateField(verbose_name='Date of Birth', blank=True, null=True,)

    # GENDER_CHOICES=(
    #     ('Male','Male'),
    #     ('Female','Female'),
    #     ('Other','Other'),
    # )

    gender = models.CharField(max_length=50, null=True, blank=True)
    
    QUALIFICATION_CHOICES = (
        ('O Level', 'O Level'),
        ('Undergraduate', 'Undergraduate'),
        ('OND/HND', 'OND/HND'),
        ("Bachelor's Degree", "Bachelor's Degree"),
        ("Master's Degree", "Master's Degree"),
        ('Other', 'Other'),
    )
    
    edu_qualification = models.CharField('Educational Qualification',max_length=50, choices=QUALIFICATION_CHOICES, null=True, blank=True)
   
    PROGRAMS_CHOICES = (
    ('Codegaminators', (
            ('Codegaminators - Animation', 'Animation'),
            ('Codegaminators - Coding', 'Coding'),
            ('Codegaminators - Database', 'Database'),
            ('Codegaminators - Game Development', 'Game Development'),
            ('Codegaminators - Hardware/Networking', 'Hardware/Networking'),
            ('Codegaminators - Photography', 'Photography'),
        )
    ),

    ('ICT and Digital Lifestyle', (
            ('ICT and Digi-Lifestyle 5:00pm', 'ICT and Digital Lifestyle - 5:00pm'),
            ('ICT and Digi-Lifestyle 6:30pm', 'ICT and Digital Lifestyle - 6:30pm'),
        )
    ),

    ('Digi-lifestyle for kids', (
            ('Digi-lifestyle for kids 9:00am', 'Digi-lifestyle for kids - 9:00am'),
            ('Digi-lifestyle for kids 1:00pm', 'Digi-lifestyle for kids - 1:00pm'),
        )
    ),
    
    ('DBA 500', (
            ('DBA 500', 'DBA 500'),
        )
    ),
    )
    
    program = models.CharField(max_length=50, choices=PROGRAMS_CHOICES)
    state_of_origin = models.CharField('State of Origin', blank=True, null=True, max_length=50)
    program_version = models.CharField('Program Version', blank=True, null=True, max_length=50)
    program_specific = models.CharField('Course', blank=True, null=True, max_length=50)
    local_govt = models.CharField('Local Government', blank=True, null=True, max_length=50)
    email = models.EmailField(max_length=254, blank=True, null=True,)
    phone_no = models.CharField('Phone Number',max_length=15, blank=True, null=True,)
    address = models.TextField(blank=True, null=True,)
    registration_date = models.DateTimeField( auto_now=False, auto_now_add=True)
    unique_id = models.CharField(max_length=15, unique=True, null=True, blank=True)
    roll_no = models.PositiveSmallIntegerField('Number of times present',null=True, blank=True, default=0)
    already_taken = models.BooleanField(default=False)
    picture = models.ImageField(upload_to = 'media/', null=True, blank=True )
    test_score = models.CharField(max_length=10, blank=True, null=True)


    def __str__(self):
        return "{0} {1}".format(self.surname, self.firstname)

    def get_absolute_url(self):
        return reverse('student_detail', kwargs={'pk': self.pk})    

    def get_percentage(self):
        total = Attendance.objects.filter(linked_student=self).count()
        present = Attendance.objects.filter(linked_student=self, present_state=True).count()
        try:
            percent = round((present/total)*100, 2)
        except ZeroDivisionError:
            percent = 0
        return percent

    def total_days(self):
        total = Attendance.objects.filter(linked_student=self).count()
        return total

class Attendance(models.Model):
    date = models.DateField( auto_now=False, auto_now_add=False)
    linked_student = models.ForeignKey(Student, on_delete=models.PROTECT, related_name='attendance')
    present_state = models.BooleanField(default=False)
    id = models.AutoField(primary_key=True)

    class Meta:
        verbose_name_plural = 'Attendance'
        ordering = ['date', 'linked_student']
        unique_together = ['date', 'linked_student']
    
    def __str__(self):
        return "{0} on {1}".format(self.linked_student, self.date)

templates/Student_Statistics.html
{% extends "base.html" %}
{% load staticfiles %}
{% block style %}
    <style type="text/css">
    .properties_table{
       min-height: 540px;
       font-size: 14px;
    }
    </style>
{% endblock %}
{% block content %}
<div class="container-fluid" id="stat-container">
    
    <div class="container-fluid px-0" id="stat-container">
        <h1 class="text-justify mb-1 px-1 pt-3" id="resp_text_7">Student List Filter</h1>
        <p class="text-justify font-weight-light px-1" id="resp_text_4">Please select an option from the drop-down menu to start filtering. Please note that the options in the dropdown menu are dependent on each other.</p>
        <hr class="mb-0 mx-1">

    </div>

    <div class="site_filter">
        <div class="container-fluid pt-4 px-0" id="stat-container">
            <div class="row justify-content-center m-0 py-3 " style="border-radius: 5px">
                <div class="col-sm-2 col-2">
                    <div class="form-group">
                        <label for="program">Programs</label>
                        <select class="form-control" id="program" 
                            url = "{%url 'get_program' %}">
                        </select>
                    </div>
                </div>
                <div class="col-sm-2 col-2">
                    <div class="form-group">
                        <label for="program_version">Program Versions</label>
                        <select class="form-control" id="program_version" 
                            url = "{%url 'get_program_version' %}">
                            <option value='all' selected>All</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-2 col-2">
                    <div class="form-group">
                        <label for="program_specific">Courses</label>
                        <select class="form-control" id="program_specific" 
                            url = "{%url 'get_program_specific' %}">
                            <option value='all' selected>All</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-2 col-2">
                    <div class="form-group">
                        <label for="state_of_origin">States</label>
                        <select class="form-control" id="state_of_origin" 
                            url = "{%url 'get_state_of_origin' %}">
                        </select>
                    </div>
                </div>
                
                
                <div class="col-sm-2 col-2">
                    <div class="form-group">
                        <label for="local_govt">Local Government Areas</label>
                        <select class="form-control" id="local_govt" url = "{%url 'get_local_govt' %}">
                            <option value='all' selected>All Regions</option>
                        </select>
                    </div>
                </div>

                <div class="col-sm-2 col-2">
                    <div class="form-group">
                        <label for="sort_by">Sort By</label>
                        <select class="form-control" id="sort_by">
                            <option selected="true"
                            disabled="disabled" value = "none">Choose an option</option>
                            <option value='unique_id'>ID Number</option>
                            <option value='registration_date'>Date Registered</option>
                            <option value='roll_no'>Times Present</option>
                        </select>
                    </div>
                </div>
                <div class="col-sm-1 col-1">
                    <div class="row justify-content-center align-self-center"
                        style="color:white; margin-top:5px;">
                        <a class="btn btn-secondary" id="display_all">Display all</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="container-fluid" id="stat-container">
        <div class="row justify-content-center border pt-2 font-weight-light" style="border-radius: 5px; border-width: 3px;">
            <div class="col-sm-4 col-4 text-center font-weight-light" id="total_number_l"> 
                <div>
                    <h3 class="font-weight-light">Total Number of Students</h3> 
                </div>
                <div id="total_number">
                    <h3 id="total_number"></h3>
                </div>
            </div>
            <div class="col-sm-4 col-4 text-center" id="female_l"> 
                <div>
                    <h4 class="font-weight-light">Female Students</h4>
                </div>
                <div id="female">
                    <h4></h4>
                </div>
            </div>
            <div class="col-sm-4 col-4 text-center" id="male_l"> 
                <div>
                    <h4 class="font-weight-light">Male Students</h4>
                </div>
                <div  id="male">
                    <h4 ></h4>
                    
                </div>
            </div>
        </div>
    
    </div>
    <section class="mb-0">
        <div class="container-fluid " id="stat-container">
            <div id = "result-count" class="text-right ">
                <span class='font-weight-bold'></span> results found.
            </div>
            <div class="row properties_table justify-content-center">
                <div id = "no_results">
                    <h5>No results found</h5>
                </div>
                <div class="" id="">
                    <table class="table table-bordered table-responsive table-hover table-striped"
                        id="list_data" data-toggle="table" url = "{% url 'listing' %}">
                            <thead>
                                <tr>
                                    <th data-field="sn">S/N</th>
                                    <th data-field="unique_id"> ID Number</th>
                                    <th data-field="surname">Surname</th>
                                    <th data-field="firstname">Firstname</th>
                                    <th data-field="middlename">Middlename</th>
                                    <th data-field="gender">Gender</th>
                                    <th data-field="program">Program</th>
                                    <th data-field="program_version">Program Version</th>
                                    <th data-field="program_specific">Course</th>
                                    <th data-field="roll_no">Times Present</th>
                                    <th data-field="state_of_origin">State of Origin</th>
                                    <th data-field="local_govt">Local Government Area</th>
                                    <th data-field="email">Email</th>
                                    <th data-field="phone_no">Phone Number</th>
                                </tr>
                            </thead>
                        <tbody id="listing">
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="row ">
                <div class="col-5 p-0">
                        <button class="btn btn-outline-primary ml-0 mr-4" onclick="exportTableToExcel('list_data')">Export to Excel File</button>
                        <button class="btn btn-outline-primary" id="download">Export to CSV File</button>
                
                </div>
                
                <div class="col-4 p-0" aria-label="navigation">
                    <ul class="pagination">
                        <li class="page-item px-4">
                            <button class="btn btn-primary page-link" id="previous">Previous</button>
                        </li>
                        <div class="border"></div>
                        <li class="page-item pull-right px-4">
                            <button class="btn btn-primary page-link" id="next">Next</button>
                        </li>
                    </ul>
                </div>
                
                
            </div>
            
            
        </div>
        
        
    </section>
</div>
{% endblock %}

{% block script %}

    

    
    
    <script>function exportTableToExcel(tableID, filename = ''){
        var downloadLink;
        var dataType = 'application/vnd.ms-excel';
        var tableSelect = document.getElementById(tableID);
        var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
        
        // Specify file name
        filename = filename?filename+'.xls':'excel_data.xls';
        
        // Create download link element
        downloadLink = document.createElement("a");
        
        document.body.appendChild(downloadLink);
        
        if(navigator.msSaveOrOpenBlob){
            var blob = new Blob(['\ufeff', tableHTML], {
                type: dataType
            });
            navigator.msSaveOrOpenBlob( blob, filename);
        }else{
            // Create a link to the file
            downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
        
            // Setting the file name
            downloadLink.download = filename;
            
            //triggering the function
            downloadLink.click();
        }
    }</script>
    
    <script src="{% static 'js/statistic.js' %}" type="text/javascript"></script>
    
    <script src="{% static 'js/table2csv.js' %}"></script>

    <script>
        $('#download').on('click',function(){
          $('table').table2csv({
            file_name: 'jqueryscript.csv',
            header_body_space: 0
          });
        })
        </script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
{% load staticfiles %}


  <head>
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block style %}
    {% endblock %}
    
    <link rel="stylesheet" href="{% static '../static/css/main.css' %}" >
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:600|Roboto+Condensed:300,400|Roboto:300,400&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script&display=swap" rel="stylesheet">  
    <title>
    
    {% block title %}
      
    {% endblock title %}
       </title>
  </head>
  
  
  <body>
    
    <nav id='nav_color' class="navbar sticky-top navbar-expand-xl navbar-light shadow-sm py-3 font-weight-normal">
    
      <a class="navbar-brand ml-5" href="{% url 'login' %}">TechCreek</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item active mx-1">
            <a class="nav-link" href="{% url 'home'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item mx-1">
            <a class="nav-link" href="{% url 'take_attendance_search'%}">Take Attendance</a>
          </li>
          <li class="nav-item mx-1">
            <a class="nav-link" href="{% url 'stu_registration'%}">Register Student</a>
          </li>
          <li class="nav-item mx-1">
            <a class="nav-link" href="{% url 'student_list' %}">Student Info</a>
          </li>
          <li class="nav-item dropdown mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Attendance Sheets
              </a>
              <div class="dropdown-menu ml-0" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'cgm_summary'%}"><i class="fa fa-code"></i> Codegaminators</a>
                <a class="dropdown-item" href="{% url 'ict_summary'%}"><i class="fa fa-laptop" aria-hidden="true"></i>  Digital Lifestyle</a>
                <a class="dropdown-item" href="{% url 'kids_summary'%}"><i class="fa fa-child"></i>  Digi-lifestyle for kids</a>
                <a class="dropdown-item" href="{% url 'dba_summary'%}"><i class="fa fa-database"></i> DBA 500</a>
                <div class="dropdown-divider"></div>
                <p class="dropdown-item mb-0" > <i class="fa fa-line-chart" aria-hidden="true" ></i><a href="{% url 'attendance'%}" id="drop_down_stats"> Student List Filter</a></p>
              </div>
            </li>
          
          
          
          {% if user.is_authenticated %}
            <li class="nav-item dropdown mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{user.username|capfirst}}
            </a>
            <div class="dropdown-menu ml-0" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'logout'%}"><i class="fa fa-sign-out" aria-hidden="true"></i>  Sign Out</a>
              
              <div class="dropdown-divider"></div>
              <p class="dropdown-item mb-0" ><i class="fa fa-user" aria-hidden="true"></i><span> </span>
              {% if user.first_name %}
                {{user.first_name|capfirst}}, {{user.last_name|capfirst}}
              {% else %}
                {{user.username}}
              {% endif %}
                 </p>
            </div>
          </li>

          {% else %}
          <li class="nav-item mx-1">
            <a class="nav-link" href="{% url 'login'%}">Sign In</a>
          </li>

          {% endif %}
            
          
          
        </ul>
        <form class="form-inline my-2 my-lg-0 mr-3" method="GET" action="{% url 'search' %}">
          <div class="input-group">
            <input class="form-control mr-0 border-right-0" type="search" placeholder="Search" aria-label="Search" name="q">
              <div class="input-group-append"> 
                  <button class="input-group-text bg-white" type="submit"><i class="fa fa-search"></i></button>
              </div>
            
          </div>
        </form>
      </div>
    
    </nav>


    {% block content %}
      
    {% endblock content %}
      
     
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" ></script>
    
    <script>
        $(document).ready(function() {
        $('li.active').removeClass('active');
        $('a[href="' + location.pathname + '"]').closest('li').addClass('active'); 
        });
    </script>
    {% block script %}
        
    {% endblock script%}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}



{% block content %}
<div class="backg-img4">
<div class="land-main container home-main" >
   <div class="row justify-content-center mt-5 " >
    
        <div class="col-4 text-justify ">
            <div class="pt-5">
            <div class="pt-5"> 
                <h1 class="text-center font-weight-light">Easy, Simple Attendance System</h1>
                <p class="text-center font-weight-light mb-0">Register students, take attendance, view attendance information and other student data. Get the data presented in an organised format.
                </p>
                
                {% if user.is_authenticated %}
                <p class="text-center font-weight-light"> Thanks for signing in and welcome, {{user.first_name|capfirst}}</p>
                <div class="row justify-content-center ">
                        <a href="{% url 'take_attendance_search'%}" class="btn btn-secondary font-weight-light ">Get Started</a>
                </div>  
                {% else %}
                <p class="text-center font-weight-light"> Get started by signing in. You won't be able to use this system if you have not.</p>
                <div class="row justify-content-center ">
                    <a href="{% url 'login'%}" class="btn btn-secondary font-weight-light ">Go Sign In</a>
                </div>
                {% endif %}
                    
            </div>
            </div>
        </div>
        <div class="col-8">
            <img src="../static/images/landing_1.png" alt="" class="img-fluid img-absolute">
        </div>
        
   </div>

    
</div>

<div id="section_1" class=''>
<div class="land-main2 container home-main">
    <div class="row justify-content-center mt-5 pt-3">
        <div class="col-8">
            <img src="../static/images/Laptop_content_full.png" alt="" class="img-fluid img-absolute">
        </div>
        
        <div class="col-4 text-justify pt-3">
                <div class="pt-5">
                <div class="pt-5"> 
                    <h1 class="text-center font-weight-light">Easy, Simple Attendance System</h1>
                    <p class="text-center font-weight-light mb-0">For recording student data, taking attendance quickly and getting data in an organized manner.
                    </p>
                    {% if user.is_authenticated %}
                <p class="text-center font-weight-light"> Thanks for signing in and welcome, {{user.first_name|capfirst}}</p>
                <div class="row justify-content-center ">
                        <a href="{% url 'home'%}" class="btn btn-secondary font-weight-light ">Get Started</a>
                </div>  
                    {% else %}
                <p class="text-center font-weight-light"> Get started by signing in. You won't be able to use this system if you have not.</p>
                <div class="row justify-content-center ">
                    <a href="{% url 'login'%}" class="btn btn-secondary font-weight-light ">Go Sign In</a>
                </div>
                    {% endif %}
                        
                </div>
            </div>
        </div>    
        
    </div>
    
</div>
<div>
    
    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
    viewBox="0 0 1440 126" style="enable-background:new 0 0 1440 126;" xml:space="preserve" >
   <style type="text/css">
       .st0{fill:rgb(119, 124, 131);}
   </style>
   <title>Rectangle 3</title>
   <desc>Created with Sketch.</desc>
   <path class="fsvg" d="M685.6,38.8C418.7-11.1,170.2,9.9,0,30v96h1440V30C1252.7,52.2,1010,99.4,685.6,38.8z"/>
   </svg>
</div>

<div class="footer_text">
   <p class="font-weight-lighter">TechCreek | Attendance</p> 
</div>

<p class="footer_sub1">
    <i class="fa fa-map-marker" aria-hidden="true"></i> Port Harcourt-Aba Expressway opposite Pleasure Park, Airforce Junction, Port Harcourt.
</p>

<p class="footer_sub2">
    <i class="fa fa-phone" aria-hidden="true"></i> 0903 000 3180
</p>

<div class="footer_sub3">
    <a href="https://www.facebook.com/techcreekng/">
        <i class="fa fa-facebook-square" aria-hidden="true" style="color: #dfdfdf"></i>
    </a>
</div>

<div class="footer_sub4">
    <a href="https://twitter.com/techcreekng?lang=en">
        <i class="fa fa-twitter-square" aria-hidden="true" style="color: #dfdfdf"></i>
    </a>
</div>

<div class="footer_sub5">
    <a href="https://www.instagram.com/techcreekng/">
        <i class="fa fa-instagram" aria-hidden="true" style="color: #dfdfdf"></i>
    </a>
</div>

<div class="footer_sub6">
        <a href="https://www.techcreek.ng">
            <i class="fa fa-home" aria-hidden="true" style="color: #dfdfdf"></i>
        </a>
</div>

<div class="footer_sub7">
    <p class="">©{% now "Y" %} TechCreek. All Rights Reserved.</p> 
</div>


<!-- <div class="container pt-5">
        <div class="row justify-content-center mt-5 pb-5">
         
             <div class="col-4 text-justify">
                 <div class="pt-5">
                 <div class="pt-5"> 
                     <h1 class="text-center font-weight-light">Easy, Simple Attendance System</h1>
                     <p class="text-center font-weight-light mb-0">For recording student data, taking attendance quickly and getting data in an organized manner.
                     </p>
                     
                     {% if user.is_authenticated %}
                     <p class="text-center font-weight-light"> Thanks for signing in and welcome, {{user.first_name|capfirst}}</p>
                     <div class="row justify-content-center ">
                             <a href="{% url 'home'%}" class="btn btn-secondary font-weight-light ">Get Started</a>
                     </div>  
                     {% else %}
                     <p class="text-center font-weight-light"> Get started by signing in. You won't be able to use this system if you have not.</p>
                     <div class="row justify-content-center ">
                         <a href="{% url 'login'%}" class="btn btn-secondary font-weight-light ">Go Sign In</a>
                     </div>
                     {% endif %}
                         
                 </div>
                 </div>
             </div>
             <div class="col-8">
                 <img src="../static/images/landing_3.png" alt="" class="img-fluid img-absolute">
             </div>
             
        </div>
     
         
     </div>

</div>      -->
{% endblock content %}

templates/statistics.html
{% extends 'base.html' %}


{% block content %}
<div class="container p-4 font-weight-light" id="">
    <div class="row justify-content-center">
        <div class="col-9 card bg-transparent shadow-sm px-2 justify-self-center" style="border-radius: 1%">
        <div class="row pt-4">
        <div class="col-7">
                <h2 class="">Total Number of Students</h2>
                <h4 class="text-center">{{total_number}}</h4>
        </div> 
        <div class="col-2">
                <h4>Females</h4>
                <h5>{{female_num}}</h5>
            </div>
            <div class="col-2">
                <h4>Males</h4>
                <h5>{{male_num}}</h5>
            </div>

        </div>

        <div class="row pt-2">
            <div class="col-12">
                <h3>Student Distribution by Programs</h3>
                <h5 class="" style="font-size: 1.5rem">Codegaminators {{cgm}} Students</h5>
            </div>
            
        </div>  


        <div class="row">
                <div class="col-4">
                    <h5>ICT and Digital Lifestyle</h5>
                    {{ict}}
                </div>
                <div class="col-4">
                        <h5>DBA 500</h5>
                        {{dba_500}}
                </div>
                <div class="col-4">
                        <h5>Digi-lifestyle for kids</h5>
                        {{kids}}
                </div>
    
        </div>

        <div class="row">
            <div class="col-12">
                <h5 class="" style="font-size: 1.5rem">Codegaminators {{cgm}} Students</h5>
            </div>
            
            <div class="col-12">
                <h5>Animation</h5>
                {{animation_num}}
            </div>
            
            <div class="col-12">
                    <h5>Coding</h5>
                    {{coding_num}}
            </div>
            <div class="col-12">
                    <h5>Database</h5>
                    {{database_num}}
            </div>
            <div class="col-12">
                    <h5>Game Development</h5>
                    {{game_dev_num}}
            </div>
            <div class="col-12">
                    <h5>Hardware</h5>
                    {{hardware_num}}
            </div>
            <div class="col-12">
                    <h5>Photography</h5>
                    {{photography_num}}
            </div>
        </div>

        

        <div class="row ">
            <div class="col-12 pt-2 ">
                <h3>Student Distribution by States</h3>
                <p>Only states that have students are shown.</p>        
            </div>    
        </div>

        <div class="row ">
            
            {% for a in states %}
                
                {% if a.student.all %}
                <div class="col-3">
                    <h5>{{a}}</h5>
                    <p>{{a.student.count}}</p>
                </div>
                {% endif %}
                    
            {% endfor %}
                

        </div>
        
        <div class="row">
                <div class="col-12">
                    <h3>Student Distribution by Local Government for River State</h3>       
                </div>    
        </div>
        <div class="row">
            
            {% for a in lga %}
                    
                
                <div class="col-3">
                    <h5>{{a}}</h5>
                    <p>{{a.student_set.count}}</p>
                </div>
                
                        
            {% endfor %}
                    
        
        </div>
        </div>
    </div>

</div> 



{% endblock content %}
    